# Generated by Django 3.2 on 2021-07-13 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0004_remove_blogpost_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='tag',
        ),
    ]
