# Generated by Django 3.2 on 2021-07-13 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0005_remove_blogpost_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='tag',
            field=models.CharField(default='#tech', max_length=500),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='image',
            field=models.FileField(default='', upload_to='static/media/'),
            preserve_default=False,
        ),
    ]
